### ISSUE TITLE
slam lib error

### ISSUE THREAD

**Issue by enginksz** [luigifreda/slamplay#3]
"Hello, 

I congratulate you on your work. 

I didn't encounter any errors during the installation:

$ ./install_dependencies.sh
$ ./install_local_opencv.sh
$ ./build.sh

I completed the installations and I also edited the config/.. yaml files to specify the dataset path in the same way.

When I run the app/run_euroc_stereo.cpp  code, I get the following error.

run_euroc_stereo.cpp:7:10: fatal error: myslam/visual_odometry.h: No such file or directory
    7 | #include "myslam/visual_odometry.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

(my command: g++ -o run_euroc_stereo run_euroc_stereo.cpp -I/home/sam/slamplay/full_slam/include -I/home/sam/slamplay/thirdparty/eigen-3.3.7 -I/home/sam/slamplay/thirdparty/Sophus -L/home/sam/slamplay/full_slam/lib -lgflags -lmyslam)

How can I solve this issue?"

**Comment by luigifreda** [comment]
Hi,
the following commands 
```
$ ./install_dependencies.sh
$ ./install_local_opencv.sh
$ ./build.sh
```
take care of installing dependencies, build the code, and generate binaries that are ready to be run. In order to run the compiled binaries you need to enter into the `build` folder and then run what you need. For instance, in your case: 
```
cd build/full_slam/app 
./run_euroc_stereo
```

The command you are using is for building the code again and not for running it. 
Cheers,
Luigi
